# Định nghĩa trực tiếp port từ file .env
@port = 80
@baseUrl = http://localhost:{{port}}

### Get all users
< {%
  client.global.headers.set('Accept', 'application/json')
  client.global.headers.set('x-special-flag', '3536AEAC-F9C3-48F4-BE9F-10AC92D5949D')
%}

GET {{baseUrl}}/users?keyword=Olga

> {%
  console.log(`Response: ${JSON.stringify(response)}`)
%}

### Get one user
GET {{baseUrl}}/users

> {%
  console.log(`Response: ${JSON.stringify(response)}`)
%}
